import React, { Component } from 'react';
import Blog from '../components/Blog';

/* To replace with reducer data */
const posts = [
  { postId: 1, location: 'Portland, OR', imageUrl: '/', body: '21 PABLO STORES WORLDWIDE THIS WEEKEND LOCATIONS HERE SCHLESISCHE STR AND OBERBAUMBRUCKE @ 2:30AM HECKMANNUFER AND SCHLESISCHE STR @ 3:00AM BERGHAIN AND AM WRIEZENER BAHNHOF @ 4:00AM LOS ANGELES FAMOUS VIEWINGS IN DALLAS TONIGHT STARTING AT N HOUSTON STREET AND ELM STREET @ 9:30PM ROSWELL ROAD AND POWERS FERRY ROAD @ 1:30AM unity love vibes AMSTERDAM PIEDMONT ROAD NE AND LINDBERGH WAY NE @ 11:30PM MORELAND AVENUE NE AND EUCLID AVENUE NE @ 12:30AM ...Frank album on repeat👌 ASK SOMEBODY Each and every one’s time, insight and feelings are invaluable to us. We want to make people feel great.This Tidal Apple beef is fucking up the music game. ATLANTA PORTLAND PIEDMONT ROAD NE AND LINDBERGH WAY NE @ 11:30PM MORELAND AVENUE NE AND EUCLID AVENUE NE @ 12:30AM' },
  { postId: 2, location: 'Portland, OR', imageUrl: '/', body: '21 PABLO STORES WORLDWIDE THIS WEEKEND LOCATIONS HERE SCHLESISCHE STR AND OBERBAUMBRUCKE @ 2:30AM HECKMANNUFER AND SCHLESISCHE STR @ 3:00AM BERGHAIN AND AM WRIEZENER BAHNHOF @ 4:00AM LOS ANGELES FAMOUS VIEWINGS IN DALLAS TONIGHT STARTING AT N HOUSTON STREET AND ELM STREET @ 9:30PM ROSWELL ROAD AND POWERS FERRY ROAD @ 1:30AM unity love vibes AMSTERDAM PIEDMONT ROAD NE AND LINDBERGH WAY NE @ 11:30PM MORELAND AVENUE NE AND EUCLID AVENUE NE @ 12:30AM ...Frank album on repeat👌 ASK SOMEBODY Each and every one’s time, insight and feelings are invaluable to us. We want to make people feel great.This Tidal Apple beef is fucking up the music game. ATLANTA PORTLAND PIEDMONT ROAD NE AND LINDBERGH WAY NE @ 11:30PM MORELAND AVENUE NE AND EUCLID AVENUE NE @ 12:30AM' },
  { postId: 3, location: 'Portland, OR', imageUrl: '/', body: '21 PABLO STORES WORLDWIDE THIS WEEKEND LOCATIONS HERE SCHLESISCHE STR AND OBERBAUMBRUCKE @ 2:30AM HECKMANNUFER AND SCHLESISCHE STR @ 3:00AM BERGHAIN AND AM WRIEZENER BAHNHOF @ 4:00AM LOS ANGELES FAMOUS VIEWINGS IN DALLAS TONIGHT STARTING AT N HOUSTON STREET AND ELM STREET @ 9:30PM ROSWELL ROAD AND POWERS FERRY ROAD @ 1:30AM unity love vibes AMSTERDAM PIEDMONT ROAD NE AND LINDBERGH WAY NE @ 11:30PM MORELAND AVENUE NE AND EUCLID AVENUE NE @ 12:30AM ...Frank album on repeat👌 ASK SOMEBODY Each and every one’s time, insight and feelings are invaluable to us. We want to make people feel great.This Tidal Apple beef is fucking up the music game. ATLANTA PORTLAND PIEDMONT ROAD NE AND LINDBERGH WAY NE @ 11:30PM MORELAND AVENUE NE AND EUCLID AVENUE NE @ 12:30AM' },
  { postId: 4, location: 'Portland, OR', imageUrl: '/', body: '21 PABLO STORES WORLDWIDE THIS WEEKEND LOCATIONS HERE SCHLESISCHE STR AND OBERBAUMBRUCKE @ 2:30AM HECKMANNUFER AND SCHLESISCHE STR @ 3:00AM BERGHAIN AND AM WRIEZENER BAHNHOF @ 4:00AM LOS ANGELES FAMOUS VIEWINGS IN DALLAS TONIGHT STARTING AT N HOUSTON STREET AND ELM STREET @ 9:30PM ROSWELL ROAD AND POWERS FERRY ROAD @ 1:30AM unity love vibes AMSTERDAM PIEDMONT ROAD NE AND LINDBERGH WAY NE @ 11:30PM MORELAND AVENUE NE AND EUCLID AVENUE NE @ 12:30AM ...Frank album on repeat👌 ASK SOMEBODY Each and every one’s time, insight and feelings are invaluable to us. We want to make people feel great.This Tidal Apple beef is fucking up the music game. ATLANTA PORTLAND PIEDMONT ROAD NE AND LINDBERGH WAY NE @ 11:30PM MORELAND AVENUE NE AND EUCLID AVENUE NE @ 12:30AM' },
];

class BlogContainer extends Component {
  render() {
    return (
      <Blog {...this.props} posts={posts} />
    );
  }
}

export default BlogContainer;
